[package]
name = "locale-translate"
version = "0.1.0"
edition = "2024"

[dependencies]
deepl-api = "0.4.3"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
serde_json = "1.0.145"
soft-canonicalize = "0.4.5"
